name: Build and Deploy train-ticket-reservation

on:
  push:
    branches:
      - practice
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name:  Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name:  Build with Maven
        run: mvn clean package -DskipTests

      - name: SonarQube Analysis
        run: |
         mvn sonar:sonar \
         -Dsonar.projectKey=train-ticket-reservation \
         -Dsonar.projectName="Train Ticket Reservation" \
         -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
         -Dsonar.login=${{ secrets.SONAR_TOKEN }}

    
